#  飞书
APP_ID: cli_axxx
APP_SECRET: xxx
APP_ENCRYPT_KEY: xxx
APP_VERIFICATION_TOKEN: xxx
# 请确保和飞书应用管理平台中的设置一致 
BOT_NAME: chatGpt
# openAI
OPENAI_KEY: sk-xxx
# api URL 默认是https://api.openai.com
API_URL: https://api.openai.com
